/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_droidlogic_imageplayer_SurfaceOverlay */

#ifndef _Included_com_droidlogic_imageplayer_SurfaceOverlay
#define _Included_com_droidlogic_imageplayer_SurfaceOverlay
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_droidlogic_imageplayer_SurfaceOverlay
 * Method:    nativeSetSurface
 * Signature: (Landroid/view/Surface;)V
 */
JNIEXPORT void JNICALL
Java_com_droidlogic_imageplayer_SurfaceOverlay_nativeSetSurface
(JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
